/**
 * Fixed prose for `thoughts help <topic>` (specs/18-cli-help.md).
 *
 * Topics are the CLI's own condensed wording: readable on their own, each one
 * naming the spec file that holds the full detail. They never read the brain,
 * the config, or the network.
 */

export interface HelpTopic {
  /** Lowercase topic name, matched exactly (no prefixes, no fuzzy match). */
  readonly name: string;
  /** One-line summary shown in the root help and in the unknown-topic error. */
  readonly summary: string;
  /** The topic text. A screenful, ending with the spec it condenses. */
  readonly text: string;
}

export const HELP_TOPICS: readonly HelpTopic[] = [
  {
    name: 'brain',
    summary: 'What a brain is, layout, zones, the symlink (specs/01-brain-repo.md)',
    text: `
The brain (specs/01-brain-repo.md)
==================================

A brain is one shared, git-backed store of OKF markdown that every repo in a
multi-repo project attaches to. It holds the intent — plans, specs, research,
decisions, PRs — while the code repos hold the code. Links run both ways: the
brain records which repo owns a thought, and each code repo carries a
.thoughts.yml naming its brain and repo id.

On your machine:

  ~/.config/thoughts/config.yml    global config: known brains, attached repos
  ~/.thoughts/brains/<brain-id>/   the brain clone (the store of record)
  <repo>/.thoughts.yml             committed: which brain, which repo id
  <repo>/thoughts                  symlink to the brain root (gitignored)

The symlink targets the brain ROOT, never a subdirectory, so
thoughts/shared/... and thoughts/repos/<other-repo>/... are reachable from any
attached repo.

Layout — three zones, and every thought lives in exactly one:

  shared/            project-wide thoughts, owned by no single repo
  repos/<repo-id>/   thoughts owned by one code repo (plans/ specs/ research/
                     decisions/ prs/)
  users/<user-id>/   optional personal scratch

The subdirectories are kinds: plans, specs, research, decisions, prs by
default; brain.yml may declare more. Every thought is an OKF markdown file
with YAML frontmatter (see: thoughts help okf).

index.md and log.md files are generated by "thoughts sync" — never hand-edit
them. repos/<id>/codegraph/ is generated data too (specs/17).

brain.yml is the brain-level config: name, repos, backend, template source.
A brain may omit templates/ and standard/; the CLI then uses its built-ins.
`,
  },
  {
    name: 'backends',
    summary: 'git / psql / nebula, the cred-ref rule, immutability (specs/16-brain-backends.md)',
    text: `
Brain backends (specs/16-brain-backends.md)
===========================================

A brain has a backend: the durable store and sync transport, chosen at init
and immutable in this version. Thoughts stay OKF markdown documents in every
backend — that part never changes.

  git (default)   a plain git repository; "git pull --rebase" / "git push".
                  The only backend that works with no server. The brain clone
                  at ~/.thoughts/brains/<id>/ IS the store.
  psql            a PostgreSQL database. Frontmatter lives as real columns
                  plus jsonb, full documents in a "thoughts" table, writes in
                  one transaction under an advisory lock with an optimistic
                  base_rev check. An append-only "history" table backs
                  "thoughts scan --history". (not in this version)
  nebula          a NebulaGraph space. Frontmatter as thought-vertex
                  properties, relations as edges (LINKS_TO, SUPERSEDES).
                  No transactions: on conflict the store wins, and sync
                  prints what was lost. History is bounded, and scan
                  --history says so rather than pretend. (not in this version)

Selection: "thoughts init --backend psql --connection-ref env:VAR".
A psql or nebula brain needs a server; if it is unreachable, init prints a
ready-to-run docker snippet and exits 2. This version ships the git backend
only; psql and nebula refuse to run (exit 1).

Workspace vs store: ~/.thoughts/brains/<brain-id>/ is the working set for
every backend — the same layout, the same OKF markdown. For psql and nebula it
is a CLI-materialised copy, fully rebuildable from the store. Nothing in the
kit or the adapters knows which backend is in use.

Credential references (the cred-ref rule): connection details NEVER live in
the brain or any committed file — brain.yml must not contain a connection
string, password, or host credential, and the scanner treats one as a
block-severity finding. brain.yml holds only non-secret descriptors (kind,
database, space). The connection itself is referenced from global config as
  env:VAR       the name of an environment variable holding the URL
  keyref:name   an entry in the OS keychain
and resolved at connect time. .thoughts.yml gains schemes: a git URL as
today, postgres:<brain-id>, nebula:<brain-id>.

Queries (status, search, --json) SHOULD be answered from the backend's own
index — column filters and FTS for psql, graph traversals for nebula, file
walks for git — never by walking markdown where a query exists.
`,
  },
  {
    name: 'secrets',
    summary: 'What the scanner blocks, allow-listing, no bypass flag (specs/15-secret-scanning.md)',
    text: `
Secret scanning (specs/15-secret-scanning.md)
=============================================

The brain is shared with everyone on the project, cloned to every machine, and
fed to AI assistants. A secret that lands there is copied everywhere at the
next sync and is very hard to recall. The scanner keeps it out — no network,
no LLM, fast enough to run on every sync.

What is scanned: every text file under the brain root (including brain.yml,
generated indexes, templates, standard/), <repo>/.thoughts.yml, and the values
passed to "thoughts new --set". Binary files and files over 1 MB are
unscannable and blocked unless allow-listed by path.

Detectors, all on by default:

  1. filename blocklist   .env*, *.pem, *.key, id_rsa*, credentials.json,
                          service-account*.json, .netrc, ... regardless of
                          content
  2. known formats        AWS, GitHub, GitLab, Slack, Google, Stripe,
                          Anthropic, OpenAI, JWT, private key blocks, database
                          connection strings (any postgres:// or mysql:// URL
                          is block severity; a cred-ref like env:VAR does not
                          fire)
  3. generic assignment   password|secret|token|api_key|... = <12+ chars> —
                          placeholder values (<...>, \${...}, {{...}}, xxx...,
                          changeme, REDACTED) are not flagged
  4. entropy (opt-in)     brain.yml security.entropy: true; warns, never
                          blocks

Where it runs: on every sync before validate (refuses to commit, exit 7), on
the brain clone's pre-commit hook (git backend), on new --set, on init, and on
"thoughts scan" over the whole brain. There is NO bypass flag.

Output masks every matched value to its first 4 characters; the full value is
never printed, logged, or cached. --json emits { path, line, kind, severity,
masked, fingerprint } per finding.

Fixing: edit the flagged lines, then rotate any real credential that was
exposed. (scan --fix and per-fingerprint allow-listing into
.brain>/.thoughts-allow.yml with a reason are specified in specs/15 but not
in this version.)
`,
  },
  {
    name: 'okf',
    summary: 'Frontmatter fields, trust tiers, generated indexes (specs/09-index-metadata-okf.md)',
    text: `
OKF metadata (specs/09-index-metadata-okf.md)
=============================================

Every thought is an OKF concept: a .md file with YAML frontmatter. The brain
is an OKF bundle; its root index.md declares okf_version: "0.2". Consumers
MUST preserve unknown frontmatter fields — the CLI never strips fields it does
not know.

Frontmatter fields:

  type          required   Plan, Spec, Research, Decision, Pull Request,
                           Commit — or an org-declared type from brain.yml
  title         required   display name
  description   should     one sentence; empty allowed in drafts (sync warns)
  resource      may        URI of the underlying asset (PR URL, code path)
  tags          may        list
  status        required   draft (default) / stable / deprecated
  stale_after   may        ISO 8601 date; status and search surface stale
                           thoughts past it
  generated     required   { by, at } — the actor that created the thought
  verified      may        list of { by, at }; drives the trust tier
  sources       may        list of { resource, title?, id? }; provenance
  repo          required   owning repo id, "shared", or "user:<id>"; must
                           agree with the path zone
  links         may        { ticket, pr, branch, work_item } (integrations)
  supersedes /  may        bundle-relative paths, for decisions
  superseded_by

Trust tiers, derived exactly as OKF:

  unverified          no verified[]
  machine-confirmed   verified[] has only non-human actors
  human-reviewed      any verified[].by starts with human:

Actor ids: humans are human:<user-id> (from global config, default the git
user.email local part); assistants set generated.by to <tool>/<model>, e.g.
claude-code/claude-fable-5-1.

Generated files (by "thoughts sync", never hand-edited):

  index.md   one per bundle root, zone, and repo. Sections are kinds in
             brain.yml order, entries sorted newest first, each
             "* [title](path) - description" plus a status suffix when not
             stable. The root index lists zones and repos with counts and a
             Recently updated section.
  log.md     append-only changelog, newest date first, derived from the git
             diff since the last sync commit. Past dates are never rewritten.
`,
  },
];

/** Look up a topic by exact name (no prefixes, no fuzzy match). */
export function findTopic(name: string): HelpTopic | undefined {
  return HELP_TOPICS.find((t) => t.name === name);
}
